<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Update Electronics')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('js/cmn.js'))
        ?>
    </head>
    <body>              
        <div class="sidenav">
            <h1 id="dashboard"><b>DASHBOARD</b><h1>
             <div class="sidemenu">
                <a href="#custMenu" data-toggle="collapse">Customer</a> 
                <div class="collapse" id="custMenu">                        
                            <a href="">New Customer Bill</a>
                            <a href="">View Customer Sales</a>
                            <a href="">Update Customer</a>
                            <a href="">View Customer Credit</a>
                            <a href="">Finance</a>
                            <a href="">Email Date Of Shop</a>                                                    
                </div>                                   
                <a href="#purchase" data-toggle="collapse">Purchase</a> 
                <div class="collapse" id="purchase">                        
                            <a href="">View Purchase Bill</a>
                            <a href="">View Products</a>
                            <a href="">Update Purchase</a>
                            <a href="">View Stock Amount</a>                                                                               
                </div>                
            </div>                                      
        </div>

        <div class="main">
            <nav class="navbar navbar-fixed-top" role="navigation">
                <div class="container">                                                                                      
                        <ul class="nav navbar-nav navbar-right">                          
                            <!-- <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li> -->
                            <li><input type="text" placeholder="Search..."></li>
                            <li class="dropdown" data-toggle="dropdown-menu"><a href="" class="dropdown-toggle" data-toggle="dropdown">Customer Support</a>
                                <ul class="dropdown-menu">
                                    <li><a href="">Customer Complaint Registration</a></li>
                                    <li><a href="">Demo And Complaint Call List</a></li>
                                    <li><a href="">Demo And Complaint Status</a></li>
                                    <li><a href="">View Demo And Complaint History</a></li>                                                                                                                                                 
                                </ul>
                            </li>
                            <li class="dropdown" data-toggle="dropdown-menu"><a href="" class="dropdown-toggle" data-toggle="dropdown">Accounting</a>
                                <ul class="dropdown-menu">
                                    <li><a href="">Divisions</a></li>
                                    <li><a href="">Account</a></li>
                                    <li><a href="">Working Account</a></li>
                                    <li><a href="">Entries</a></li>                                                                                                                                                 
                                    <li><a href="">Ledger</a></li>
                                    <li><a href="">Balance Sheet</a></li>                                                                                                                                                 
                                </ul>
                            </li>
                            <li class="dropdown" data-toggle="dropdown-menu"><a href="" class="dropdown-toggle" data-toggle="dropdown">Settings</a>
                                <ul class="dropdown-menu">
                                    <li><a href="">Email Data</a></li>
                                    <li><a href="">Check Quantity</a></li>
                                    <li><a href="">Backup Data</a></li>
                                    <li><a href="">Restore Data</a></li>
                                    <li><a href="">Barcode Generator</a></li>
                                    <li><a href="">Calculator</a></li>
                                    <li><a href="">Change Password</a></li>
                                    <li><a href="">Help</a></li>                                                                                                                                          
                                </ul>
                            </li>
                            <li class="dropdown" data-toggle="dropdown-menu"><a href="" class="dropdown-toggle" data-toggle="dropdown">Finance</a>
                                <ul class="dropdown-menu">
                                    <li><a href="">Add New Details</a></li>
                                    <li><a href="">View Details</a></li>                                                                                                                                                
                                </ul>
                            </li>
                            <li class="dropdown" data-toggle="dropdown-menu"><a href="" class="dropdown-toggle" data-toggle="dropdown">View</a>
                                <ul class="dropdown-menu">
                                    <li><a href="">Customer</a></li>
                                    <li><a href="">Customer Sales Account</a></li>
                                    <li><a href="">Customer Credit Account</a></li>
                                    <li><a href="">Purchase Ledger</a></li>
                                    <li><a href="">Stock Account</a></li>
                                    <li><a href="">Product</a></li>
                                    <li><a href="">Vendor Stock</a></li>
                                    <li><a href="">Customer Returns</a></li>
                                    <li><a href="">Purchase Returns</a></li>
                                    <li><a href="">Quotation</a></li>
                                    <li><a href="">Bills By Employee</a></li>                                                                                                            
                                </ul>
                            </li>
                            <li class="dropdown" data-toggle="dropdown-menu"><a href="" class="dropdown-toggle" data-toggle="dropdown">Update</a>
                                 <ul class="dropdown-menu">
                                    <li><a href="">Vendor</a></li>
                                    <li><a href="">Company/Firm</a></li>                                    
                                    <li><a href="">Customer</a></li>
                                    <li><a href="">Customer Credit Amount</a></li>
                                    <li><a href="">Customer Sale Returns</a></li>
                                    <li><a href="">Purchase Bill</a></li>
                                    <li><a href="">Purchase Credit Amount</a></li>
                                    <li><a href="">Purchase Returns</a></li>                                                                                                            
                                </ul>
                            </li>
                            <li class="dropdown" data-toggle="dropdown-menu"><a href="" class="dropdown-toggle" data-toggle="dropdown">Add</a></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/customer/addcustomerbill">Customer Bill</a></li>
                                    <li><a href="/purchase/addpurchasebill">Purchase Bill</a></li>
                                    <li><a href="/customer/createQuotation">Quotation</a></li>
                                    <li><a href="/customer/addCustomer">Customer</a></li>
                                    <li><a href="/purchase/addVendor">Vendor</a></li>
                                    <li><a href="/purchase/addProduct">Product</a></li>                                    
                                    <li><a href="">Company/Firm</a></li>
                                    <li><a href="">User</a></li>                                                                        
                                </ul>
                            </li>
                            <li><a href="<?= $this->url('home') ?>">Account</a></li>
                        </ul>                    
                </div>
            </nav>            
            <div class="row" id="contentDiv">
                <div class="col-sm-12 col-md-12 col-lg-12"> 
                    <?php echo $this->content;?>
                </div>
            </div>
        </div>   
        <script>
            $('ul li.dropdown').hover(function() {
                  $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(500);
                  }, function() {
                  $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(500);
            });
        </script>             
    </body>
</html>
