<p><a href="" class="path">Home</a> \ <span class="path">Add Customer</span></p>
 
<div class="whiteBack">
    <div class="col-sm-6 col-md-6 col-lg-6 contentStyle">
        <div class="row">
            <h4>Customer Details</h4>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <p>Name</p>
                <p>Mobile No 1</p>
                <p>Mobile No 2</p>
                <p>Email</p>
                <p>Adhar</p>
                <p>PAN</p>
                <p>GST NO</p>            
                <p>Date</p>
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <input type="text" name="custName" />
                <input type="text" name="mobNo1" />
                <input type="text" name="mobNo2" />
                <input type="text" name="email" />
                <input type="text" name="adhar" />
                <input type="text" name="pan" />
                <input type="text" name="gstNO" />
                <input type="text" name="custDate" />            
            </div>
        </div><br>    
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 contentStyle">
        <div class="row">   
            <h4 style="color:white">Customer Details</h4>     
            <div class="col-sm-4 col-md-4 col-lg-4">
                <p>Nominee Name</p>
                <p>Nominee Date</p>
                <p>Nominee Mobile</p>        
                <p>Address</p>
                <p>PIN code</p>
                <p>District</p>
                <p>State</p>
                <p>Country</p>                                    
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <input type="text" name="nomName" />
                <input type="text" name="nomDate" />
                <input type="text" name="nomMob" /> 
                <input type="text" name="custAdd" />
                <input type="text" name="pin" />
                <input type="text" name="district" />
                <input type="text" name="state" />
                <input type="text" name="country" />           
            </div>
        </div><br>           
    </div>

    <div class="row ">    
        <div class="col-sm-12 col-md-12 col-lg-12 summary">
            <div class="col-sm-2 col-md-2 col-lg-2">
                <h4 style="color:rgb(10,21,41)">Price with GST</h4>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <!-- <h4><b>Rs. 850</b></h4> -->
            </div>        
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-refresh"></button>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-plus">&nbsp;Docs</button>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-plus">&nbsp;Customer</button>
            </div>
        </div>
    </div>
</div>