<p><a href="" class="path">Home</a> \ <span class="path">Add Customer Bill</span></p>
 
<div class="whiteBack">
    <div class="col-sm-6 col-md-6 col-lg-6 contentStyle">
        <div class="row">
            <h4>Bill Details</h4>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <p>Bill Number</p>
                <p>Employee Name</p>
                <p>Date</p>
                <p>Book Number</p>
                <p>Payment</p>            
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <input type="text" name="billNo" />
                <input type="text" name="empName" />
                <input type="text" name="date" />
                <input type="text" name="bookNo" />
                <input type="text" name="payment" />
            </div>
        </div><br>
        <div class="row">
            <h4>Order Details</h4>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <p>Product Barcode</p>
                <p>product Name</p>
                <p>Product Type</p>
                <p>Product Subtype</p>
                <p>Product Size</p>            
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <input type="text" name="prdctBarcode" />
                <input type="text" name="prdctName" />
                <input type="text" name="prdctType" />
                <input type="text" name="prdctSubType" />
                <input type="text" name="prdctSize" />
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 contentStyle">
        <div class="row">
            <h4>Customer Details</h4>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <p>Name</p>
                <p>Mobile Number</p>
                <p>Address</p>                        
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <input type="text" name="custName" />
                <input type="text" name="mobNo" />
                <input type="text" name="address" class="address"/>            
            </div>
        </div><br>
        <div class="row">        
            <div class="col-sm-4 col-md-4 col-lg-4 orderDetailsDiv">
                <p>Available Quantity</p>
                <p>Taken Quantity</p>
                <p>Discount</p>
                <p>Sale</p>
                <p></p>            
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8 orderDetailsDiv">
                <input type="text" name="avlQty" />
                <input type="text" name="takenQty" />
                <input type="text" name="discount" />
                <input type="text" name="sale" />            
            </div>
        </div>       
    </div>

    <div class="row ">    
        <div class="col-sm-12 col-md-12 col-lg-12 summary">
            <div class="col-sm-2 col-md-2 col-lg-2">
                <h4>Price with GST</h4>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <h4><b>Rs. 850</b></h4>
            </div>        
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-refresh"></button>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-plus">&nbsp;Docs</button>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-plus">&nbsp;Bill</button>
            </div>
        </div>
    </div>
</div>
