<p><a href="" class="path">Home</a> \ <span class="path">Create quotation</span></p>
 
<div class="whiteBack">
    <div class="col-sm-6 col-md-6 col-lg-6 contentStyle">
        <div class="row">
            <h4>Customer Details</h4>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <p>Name</p>
                <p>Mobile No</p>
                <p>Address</p>                        
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <input type="text" name="custName" />
                <input type="text" name="mobileNo" />
                <input type="text" name="custAddress" class="address" />
            </div>
        </div><br>
        <div class="row">
            <h4>Order Details</h4>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <p>Product Barcode</p>
                <p>product Name</p>
                <p>Product Type</p>                      
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <input type="text" name="prdctBarcode" />
                <input type="text" name="prdctName" />
                <input type="text" name="prdctType" />            
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 contentStyle">
        <div class="row">
            <h4>Shop Details</h4>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <p>Company/Firm</p>
                <p>Mobile Number</p>
                <p>Address</p>                        
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <input type="text" name="CompName" />
                <input type="text" name="mobNo" />
                <input type="text" name="compAddress" class="address"/>            
            </div>
        </div><br>
        <div class="row">        
            <div class="col-sm-4 col-md-4 col-lg-4 orderDetails">    
                <p>Product Subtype</p>
                <p>Product Size</p>          
                <p>Quantity</p>                            
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8 orderDetails">    
                <input type="text" name="prdctSubType" />
                <input type="text" name="prdctSize" />
                <input type="text" name="takenQty" />                        
            </div>
        </div>       
    </div>

    <div class="row ">    
        <div class="col-sm-12 col-md-12 col-lg-12 summary">
            <div class="col-sm-2 col-md-2 col-lg-2">
                <h4 style="color:rgb(10,21,41)">Price with GST</h4>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <!-- <h4><b>Rs. 850</b></h4> -->
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <!-- <button class="glyphicon glyphicon-plus">&nbsp;Docs</button> -->
            </div>        
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-refresh"></button>
            </div>        
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-plus">&nbsp;Quotation</button>
            </div>
        </div>
    </div>
</div>