<p><a href="" class="path">Home</a> \ <span class="path">Add Product</span></p>
 
<div class="whiteBack">
    <div class="col-sm-6 col-md-6 col-lg-6 contentStyle">
        <div class="row">
            <h4>Product Details</h4>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <p>Brand Name</p>
                <p>Type</p>
                <p>Subtype</p>            
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <input type="text" name="brandName" />
                <input type="text" name="prodType" />
                <input type="text" name="prodSubType" />        
            </div>
        </div><br>    
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 contentStyle">
        <div class="row">   
            <h4 style="color:white">Product Details</h4>     
            <div class="col-sm-4 col-md-4 col-lg-4">            
                <p>Model No</p>
                <p>Size</p>
                <p>Pattern</p>                                                            
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">            
                <input type="text" name="modelNo" />
                <input type="text" name="prodSize" /> 
                <input type="text" name="prodPattern" />                                 
            </div>
        </div><br>           
    </div>

    <div class="row ">    
        <div class="col-sm-12 col-md-12 col-lg-12 summary">
            <div class="col-sm-2 col-md-2 col-lg-2">
                <h4 style="color:rgb(10,21,41)">Price with GST</h4>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <!-- <h4><b>Rs. 850</b></h4> -->
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <!-- <button class="glyphicon glyphicon-plus">&nbsp;Docs</button> -->
            </div>        
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-refresh"></button>
            </div>        
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-plus">&nbsp;Product</button>
            </div>
        </div>
    </div>
</div>