<p><a href="" class="path">Home</a> \ <span class="path">Add Vendor</span></p>
 
<div class="whiteBack">
    <div class="col-sm-6 col-md-6 col-lg-6 contentStyle">
        <div class="row">
            <h4>Vendor Details</h4>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <p>Name</p>
                <p>Owner Name</p>
                <p>Mobile No</p>
                <p>GSTIN</p>
                <p>Details</p>            
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <input type="text" name="vendName" />
                <input type="text" name="ownerName" />
                <input type="text" name="mobNo" />
                <input type="text" name="gst" />
                <input type="text" name="details"  class="address"/>                       
            </div>
        </div><br>    
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 contentStyle">
        <div class="row">   
            <h4 style="color:white">Vendor Details</h4>     
            <div class="col-sm-4 col-md-4 col-lg-4">            
                <p>City</p>
                <p>District</p>
                <p>State</p>        
                <p>Country</p>                  
                <p>Address</p>                                         
            </div>
            <div class="col-sm-8 col-md-8 col-lg-8">            
                <input type="text" name="city" />
                <input type="text" name="district" /> 
                <input type="text" name="state" />
                <input type="text" name="country" />
                <input type="text" name="address" class="address" />                     
            </div>
        </div><br>           
    </div>

    <div class="row ">    
        <div class="col-sm-12 col-md-12 col-lg-12 summary">
            <div class="col-sm-2 col-md-2 col-lg-2">
                <h4 style="color:rgb(10,21,41)">Price with GST</h4>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <!-- <h4><b>Rs. 850</b></h4> -->
            </div>        
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-refresh"></button>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-plus">&nbsp;Docs</button>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2">
                <button class="glyphicon glyphicon-plus">&nbsp;Vendor</button>
            </div>
        </div>
    </div>
</div>
